### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Adam Carter",
    "company": "West Company",
    "address": "antohter random address with a post code",
    "phone": "021154254",
    "email": "adam.carter@test.co.nz",
    "password": "secret1234"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "adam.carter@test.co.nz",
    "password": "secret1234"
}

### User a user profile endpoint
Get http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYW0uY2FydGVyQHRlc3QuY28ubnoiLCJpYXQiOjE2MzEwMzc2NTgsImV4cCI6MTYzMTAzODU1OH0.wYGPEi46NwLOHkCO8nmQNvtqwbUSD-obH2GO3vfrpY8


### Token routers

### Get refreshed Token
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYW0uY2FydGVyQHRlc3QuY28ubnoiLCJpYXQiOjE2MzEwMzc2NTgsImV4cCI6MTYzMzYyOTY1OH0.O62052VhS5Vm9seXsuGZHLL_D3i8jvdWrUjgi7TYuOw

#### Password reset request endpoints
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "adam.carter@test.co.nz"
}

#### Update new password endpoint
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "adam.carter@test.co.nz",
    "pin": "659225",
    "newPassword": "secret1234"
}

#### user logout endpoint
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYW0uY2FydGVyQHRlc3QuY28ubnoiLCJpYXQiOjE2MzEwMzc2NTgsImV4cCI6MTYzMTAzODU1OH0.wYGPEi46NwLOHkCO8nmQNvtqwbUSD-obH2GO3vfrpY8