### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Adam Carter",
    "company": "West Company",
    "address": "antohter random address with a post code",
    "phone": "021154254",
    "email": "adam.carter@test.co.nz",
    "password": "secret1234"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "adam.carter@test.co.nz",
    "password": "secret1234"
}

### User a user profile endpoint
Get http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYW0uY2FydGVyQHRlc3QuY28ubnoiLCJpYXQiOjE2Mjk4NzA0MzUsImV4cCI6MTYyOTg3MTMzNX0.79w1i6ED_iiBVQ9hQqi4xcsAD2OAxMxuXSn6AwHGDuI


### Token routers

### Get refreshed Token
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYW0uY2FydGVyQHRlc3QuY28ubnoiLCJpYXQiOjE2Mjk4NzA0MzUsImV4cCI6MTYzMjQ2MjQzNX0.lfWUE2I8_fVUaIAByC71vMwpAQ60ez5ubc5awPchhJw

#### Password reset request endpoints
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "adam.carter@test.co.nz"
}

#### Update new password endpoint
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "adam.carter@test.co.nz",
    "pin": "826097",
    "newPassword": "secret1234"
}